name: hackstorage
description: This is a project named "HackStorage". This App is about a password storage. To store the passwords, an account (Google or Email) will be required to register the passwords, either locally or on a cloud server.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/